export const allBlacksPlayers = [
  {
    key: "beaudenBarrett",
    title: "Beauden Barrett",
    firstname: "Beauden",
    lastname: "Barrett",
    teams: ["allBlacks"],
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "richieMounga",
    title: "Richie Mounga",
    firstname: "Richie",
    lastname: "Mounga",
    teams: ["allBlacks"],
    positions: ["flyhalf"],
  },
  {
    key: "aaronSmith",
    title: "Aaron Smith",
    firstname: "Aaron",
    lastname: "Smith",
    teams: ["allBlacks"],
    positions: ["scrumhalf"],
  },
  {
    key: "ardieSavea",
    title: "Ardie Savea",
    firstname: "Ardie",
    lastname: "Savea",
    teams: ["allBlacks"],
    positions: ["backrow"],
  },
  {
    key: "shannonFrizell",
    title: "Shannon Frizell",
    firstname: "Shannon",
    lastname: "Frizell",
    teams: ["allBlacks"],
    positions: ["backrow"],
  },
  {
    key: "samCane",
    title: "Sam Cane",
    firstname: "Sam",
    lastname: "Cane",
    teams: ["allBlacks"],
    positions: ["backrow"],
  },
  {
    key: "brodieRetallick",
    title: "Brodie Retallick",
    firstname: "Brodie",
    lastname: "Retallick",
    teams: ["allBlacks"],
    positions: ["lock"],
  },
  {
    key: "leicesterFaingaanuku",
    title: "Leicester Fainga’anuku",
    firstname: "Leicester",
    lastname: "Fainga’anuku",
    teams: ["allBlacks"],
    positions: ["outsideBack"],
  }
]