export const drua = [
  {
    key: "tevitaIkanivere",
    title: "Tevita Ikanivere",
    firstname: "Tevita",
    lastname: "Ikanivere",
    teams: ["drua"],
    positions: ["hooker"],
  },
  {
    key: "iosefoMasi",
    title: "Iosefo Masi",
    firstname: "Iosefo",
    lastname: "Masi",
    teams: ["drua"],
    positions: ["centre", "outsideBack"],
  },
  {
    key: "selestinoRavutaumada",
    title: "Selestino Ravutaumada",
    firstname: "Selestino",
    lastname: "Ravutaumada",
    teams: ["drua"],
    positions: ["outsideBack"],
  },
  {
    key: "frankLomani",
    title: "Frank Lomani",
    firstname: "Frank",
    lastname: "Lomani",
    teams: ["drua"],
    positions: ["scrumhalf"],
  },
  {
    key: "apisalomeVota",
    title: "Apisalome Vota",
    firstname: "Apisalome",
    lastname: "Vota",
    teams: ["drua"],
    positions: ["centre"],
  },
  {
    key: "kitioneSalawa",
    title: "Kitione Salawa",
    firstname: "Kitione",
    lastname: "Salawa",
    teams: ["drua"],
    positions: ["backrow"],
  },
  {
    key: "viliveMiramira",
    title: "Vilive Miramira",
    firstname: "Vilive",
    lastname: "Miramira",
    teams: ["drua"],
    positions: ["backrow"],
  },
  {
    key: "tanielaRakuro",
    title: "Taniela Rakuro",
    firstname: "Taniela",
    lastname: "Rakuro",
    teams: ["drua"],
    positions: ["outsideBack"],
  },
  {
    key: "haereitiHetet",
    title: "Haereiti Hetet",
    firstname: "Haereiti",
    lastname: "Hetet",
    teams: ["drua"],
    positions: ["prop"],
  },
  {
    key: "ilaisaDroasese",
    title: "Ilaisa Droasese",
    firstname: "Ilaisa",
    lastname: "Droasese",
    teams: ["drua"],
    positions: ["outsideBack"],
  },
  {
    key: "eliaCanakaivata",
    title: "Elia Canakaivata",
    firstname: "Elia",
    lastname: "Canakaivata",
    teams: ["drua"],
    positions: ["backrow"],
  },
  {
    key: "meliDerenalagi",
    title: "Meli Derenalagi",
    firstname: "Meli",
    lastname: "Derenalagi",
    teams: ["drua"],
    positions: ["backrow"],
  },
  {
    key: "peniMatawalu",
    title: "Peni Matawalu",
    firstname: "Peni",
    lastname: "Matawalu",
    teams: ["drua"],
    positions: ["scrumhalf"],
  },
  {
    key: "isoaNasilasila",
    title: "Isoa Nasilasila",
    firstname: "Isoa",
    lastname: "Nasilasila",
    teams: ["drua"],
    positions: ["lock"],
  },
  {
    key: "calebMuntz",
    title: "Caleb Muntz",
    firstname: "Caleb",
    lastname: "Muntz",
    teams: ["drua"],
    positions: ["flyhalf"],
  },
  {
    key: "kemuValetini",
    title: "Kemu Valetini",
    firstname: "Kemu",
    lastname: "Valetini",
    teams: ["drua"],
    positions: ["flyhalf"],
  },
  {
    key: "te ahiwaruCirikidaveta",
    title: "Te Ahiwaru Cirikidaveta",
    firstname: "Te Ahiwaru",
    lastname: "Cirikidaveta",
    teams: ["drua"],
    positions: ["lock", "backrow"],
  },
  {
    key: "michaelNaitokani",
    title: "Michael Naitokani",
    firstname: "Michael",
    lastname: "Naitokani",
    teams: ["drua"],
    positions: ["centre"],
  },
  {
    key: "ratuRotuisolia",
    title: "Ratu Rotuisolia",
    firstname: "Ratu",
    lastname: "Rotuisolia",
    teams: ["drua"],
    positions: ["lock"],
  },
  {
    key: "tuidrakiSamusamuvodre",
    title: "Tuidraki Samusamuvodre",
    firstname: "Tuidraki",
    lastname: "Samusamuvodre",
    teams: ["drua"],
    positions: ["outsideBack"],
  },
  {
    key: "philipBaselala",
    title: "Philip Baselala",
    firstname: "Philip",
    lastname: "Baselala",
    teams: ["drua"],
    positions: ["scrumhalf"],
  },
  {
    key: "epeliMomo",
    title: "Epeli Momo",
    firstname: "Epeli",
    lastname: "Momo",
    teams: ["drua"],
    positions: ["outsideBack"],
  },
  {
    key: "epeliWaqaicece",
    title: "Epeli Waqaicece",
    firstname: "Epeli",
    lastname: "Waqaicece",
    teams: ["drua"],
    positions: ["centre"],
  },
  {
    key: "etoniaWaqa",
    title: "Etonia Waqa",
    firstname: "Etonia",
    lastname: "Waqa",
    teams: ["drua"],
    positions: ["lock", "backrow"],
  },
  {
    key: "isaiahRavula",
    title: "Isaiah Ravula",
    firstname: "Isaiah",
    lastname: "Ravula",
    teams: ["drua"],
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "isikeliRabitu",
    title: "Isikeli Rabitu",
    firstname: "Isikeli",
    lastname: "Rabitu",
    teams: ["drua"],
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "motikiaiMurray",
    title: "Motikiai Murray",
    firstname: "Motikiai",
    lastname: "Murray",
    teams: ["drua"],
    positions: ["backrow"],
  },
  {
    key: "sailosiVukalokalo",
    title: "Sailosi Vukalokalo",
    firstname: "Sailosi",
    lastname: "Vukalokalo",
    teams: ["drua"],
    positions: ["lock"],
  },
  {
    key: "simioneKuruvoli",
    title: "Simione Kuruvoli",
    firstname: "Simione",
    lastname: "Kuruvoli",
    teams: ["drua"],
    positions: ["scrumhalf"],
  },
  {
    key: "mesakeDoge",
    title: "Mesake Doge",
    firstname: "Mesake",
    lastname: "Doge",
    teams: ["drua"],
    positions: ["prop"],
  },
  {
    key: "mesulameDolokoto",
    title: "Mesulame Dolokoto",
    firstname: "Mesulame",
    lastname: "Dolokoto",
    teams: ["drua"],
    positions: ["hooker"],
  },
  {
    key: "joneKoroiduadua",
    title: "Jone Koroiduadua",
    firstname: "Jone",
    lastname: "Koroiduadua",
    teams: ["drua"],
    positions: ["prop"],
  },
  {
    key: "livaiNatave",
    title: "Livai Natave",
    firstname: "Livai",
    lastname: "Natave",
    teams: ["drua"],
    positions: ["prop"],
  },
  {
    key: "samuelaTawake",
    title: "Samuela Tawake",
    firstname: "Samuela",
    lastname: "Tawake",
    teams: ["drua"],
    positions: ["prop"],
  },
  {
    key: "zurielTogiatama",
    title: "Zuriel Togiatama",
    firstname: "Zuriel",
    lastname: "Togiatama",
    teams: ["drua"],
    positions: ["hooker"],
  },
  {
    key: "meliTuni",
    title: "Meli Tuni",
    firstname: "Meli",
    lastname: "Tuni",
    teams: ["drua"],
    positions: ["prop"],
  },
  {
    key: "emosiTuqiri",
    title: "Emosi Tuqiri",
    firstname: "Emosi",
    lastname: "Tuqiri",
    teams: ["drua"],
    positions: ["prop"],
  }
]