export const waratahs = [
  {
    key: "angusBell",
    title: "Angus Bell",
    firstname: "Angus",
    lastname: "Bell",
    teams: ["superRugby", "waratahs", "wallabies"],
    positions: ["prop"],
  },
  {
    key: "davidPorecki",
    title: "David Porecki",
    firstname: "David",
    lastname: "Porecki",
    teams: ["superRugby", "waratahs", "wallabies"],
    positions: ["hooker"],
  },
  {
    key: "markNawaqanitawase",
    title: "Mark Nawaqanitawase",
    firstname: "Mark",
    lastname: "Nawaqanitawase",
    teams: ["superRugby", "waratahs", "wallabies"],
    positions: ["outsideBack"],
  },
  {
    key: "harryJohnson-Holmes",
    title: "Harry Johnson-Holmes",
    firstname: "Harry",
    lastname: "Johnson-Holmes",
    teams: ["superRugby", "waratahs", "wallabies"],
    positions: ["prop"],
  },
  {
    key: "langiGleeson",
    title: "Langi Gleeson",
    firstname: "Langi",
    lastname: "Gleeson",
    teams: ["superRugby", "waratahs", "wallabies"],
    positions: ["backrow"],
  },
  {
    key: "dylanPietsch",
    title: "Dylan Pietsch",
    firstname: "Dylan",
    lastname: "Pietsch",
    teams: ["superRugby", "waratahs"],
    positions: ["outsideBack"],
  },
  {
    key: "maxJorgensen",
    title: "Max Jorgensen",
    firstname: "Max",
    lastname: "Jorgensen",
    teams: ["superRugby", "waratahs", "wallabies"],
    positions: ["outsideBack"],
  },
  {
    key: "jedHolloway",
    title: "Jed Holloway",
    firstname: "Jed",
    lastname: "Holloway",
    teams: ["superRugby", "waratahs", "wallabies"],
    positions: ["lock", "backrow"],
  },
  {
    key: "izaiaPerese",
    title: "Izaia Perese",
    firstname: "Izaia",
    lastname: "Perese",
    teams: ["superRugby", "waratahs", "wallabies"],
    positions: ["centre", "outsideBack"],
  },
  {
    key: "jakeGordon",
    title: "Jake Gordon",
    firstname: "Jake",
    lastname: "Gordon",
    teams: ["superRugby", "waratahs", "wallabies"],
    positions: ["scrumhalf"],
  },
  {
    key: "milesAmatosero",
    title: "Miles Amatosero",
    firstname: "Miles",
    lastname: "Amatosero",
    teams: ["superRugby", "waratahs"],
    positions: ["lock"],
  },
  {
    key: "lalakaiFoketi",
    title: "Lalakai Foketi",
    firstname: "Lalakai",
    lastname: "Foketi",
    teams: ["superRugby", "waratahs"],
    positions: ["centre"],
  },
  {
    key: "taneEdmed",
    title: "Tane Edmed",
    firstname: "Tane",
    lastname: "Edmed",
    teams: ["superRugby", "waratahs"],
    positions: ["flyhalf", "centre"],
  },
  {
    key: "charlieGamble",
    title: "Charlie Gamble",
    firstname: "Charlie",
    lastname: "Gamble",
    teams: ["superRugby", "waratahs"],
    positions: ["backrow"],
  },
  {
    key: "hughSinclair",
    title: "Hugh Sinclair",
    firstname: "Hugh",
    lastname: "Sinclair",
    teams: ["superRugby", "waratahs"],
    positions: ["backrow", "lock"],
  },
  {
    key: "nedHanigan",
    title: "Ned Hanigan",
    firstname: "Ned",
    lastname: "Hanigan",
    teams: ["superRugby", "waratahs"],
    positions: ["lock", "backrow"],
  },
  {
    key: "joeyWalton",
    title: "Joey Walton",
    firstname: "Joey",
    lastname: "Walton",
    teams: ["superRugby", "waratahs"],
    positions: ["centre", "outsideBack"],
  },
  {
    key: "moseseTuipulotu",
    title: "Mosese Tuipulotu",
    firstname: "Mosese",
    lastname: "Tuipulotu",
    teams: ["superRugby", "waratahs"],
    positions: ["centre"],
  },
  {
    key: "lachlanSwinton",
    title: "Lachlan Swinton",
    firstname: "Lachlan",
    lastname: "Swinton",
    teams: ["superRugby", "waratahs"],
    positions: ["backrow"],
  },
  {
    key: "teddyWilson",
    title: "Teddy Wilson",
    firstname: "Teddy",
    lastname: "Wilson",
    teams: ["superRugby", "waratahs"],
    positions: ["scrumhalf"],
  },
  {
    key: "jackBowen",
    title: "Jack Bowen",
    firstname: "Jack",
    lastname: "Bowen",
    teams: ["superRugby", "waratahs"],
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "fergusLee-Warner",
    title: "Fergus Lee-Warner",
    firstname: "Fergus",
    lastname: "Lee-Warner",
    teams: ["superRugby", "waratahs"],
    positions: ["backrow", "lock"],
  },
  {
    key: "jackGrant",
    title: "Jack Grant",
    firstname: "Jack",
    lastname: "Grant",
    teams: ["superRugby", "waratahs"],
    positions: ["scrumhalf"],
  },
  {
    key: "harryWilson",
    title: "Harry Wilson",
    firstname: "Harry",
    lastname: "Wilson",
    teams: ["superRugby", "waratahs"],
    positions: ["outsideBack", "centre"],
  },
  {
    key: "mesuKunavula",
    title: "Mesu Kunavula",
    firstname: "Mesu",
    lastname: "Kunavula",
    teams: ["superRugby", "waratahs"],
    positions: ["backrow"],
  },
  {
    key: "nedSlack-Smith",
    title: "Ned Slack-Smith",
    firstname: "Ned",
    lastname: "Slack-Smith",
    teams: ["superRugby", "waratahs"],
    positions: ["backrow"],
  },
  {
    key: "vuateKarawalevu",
    title: "Vuate Karawalevu",
    firstname: "Vuate",
    lastname: "Karawalevu",
    teams: ["superRugby", "waratahs"],
    positions: ["outsideBack"],
  },
  {
    key: "willHarrison",
    title: "Will Harrison",
    firstname: "Will",
    lastname: "Harrison",
    teams: ["superRugby", "waratahs"],
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "danielBotha",
    title: "Daniel Botha",
    firstname: "Daniel",
    lastname: "Botha",
    teams: ["superRugby", "waratahs"],
    positions: ["prop"],
  },
  {
    key: "theoFourie",
    title: "Theo Fourie",
    firstname: "Theo",
    lastname: "Fourie",
    teams: ["superRugby", "waratahs"],
    positions: ["hooker"],
  },
  {
    key: "archerHolz",
    title: "Archer Holz",
    firstname: "Archer",
    lastname: "Holz",
    teams: ["superRugby", "waratahs"],
    positions: ["prop"],
  },
  {
    key: "tomLambert",
    title: "Tom Lambert",
    firstname: "Tom",
    lastname: "Lambert",
    teams: ["superRugby", "waratahs"],
    positions: ["prop"],
  },
  {
    key: "tomRoss",
    title: "Tom Ross",
    firstname: "Tom",
    lastname: "Ross",
    teams: ["superRugby", "waratahs"],
    positions: ["prop"],
  },
  {
    key: "haydenThompson-Stringer",
    title: "Hayden Thompson-Stringer",
    firstname: "Hayden",
    lastname: "Thompson-Stringer",
    teams: ["superRugby", "waratahs"],
    positions: ["prop"],
  },
  {
    key: "maheVailanu",
    title: "Mahe Vailanu",
    firstname: "Mahe",
    lastname: "Vailanu",
    teams: ["superRugby", "waratahs"],
    positions: ["hooker"],
  }
]