export const rebels = [
  {
    key: "carterGordon",
    title: "Carter Gordon",
    firstname: "Carter",
    lastname: "Gordon",
    team: "Rebels",
    position: "flyhalf",
    positions: ["flyhalf"],
  },
  {
    key: "andrewKellaway",
    title: "Andrew Kellaway",
    firstname: "Andrew",
    lastname: "Kellaway",
    team: "Rebels",
    position: "outsideBack",
    positions: ["outsideBack", "centre"],
  },
  {
    key: "mattProctor",
    title: "Matt Proctor",
    firstname: "Matt",
    lastname: "Proctor",
    team: "Rebels",
    position: "centre",
    positions: ["centre"],
  },
  {
    key: "joshKemeny",
    title: "Josh Kemeny",
    firstname: "Josh",
    lastname: "Kemeny",
    team: "Rebels",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "ryanLouwrens",
    title: "Ryan Louwrens",
    firstname: "Ryan",
    lastname: "Louwrens",
    team: "Rebels",
    position: "scrumhalf",
    positions: ["scrumhalf"],
  },
  {
    key: "alexMafi",
    title: "Alex Mafi",
    firstname: "Alex",
    lastname: "Mafi",
    team: "Rebels",
    position: "hooker",
    positions: ["hooker"],
  },
  {
    key: "filipoDaugunu",
    title: "Filipo Daugunu",
    firstname: "Filipo",
    lastname: "Daugunu",
    team: "Rebels",
    position: "outsideBack",
    positions: ["outsideBack", "centre"],
  },
  {
    key: "joshCanham",
    title: "Josh Canham",
    firstname: "Josh",
    lastname: "Canham",
    team: "Rebels",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "lachieAnderson",
    title: "Lachie Anderson",
    firstname: "Lachie",
    lastname: "Anderson",
    team: "Rebels",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "bradWilkin",
    title: "Brad Wilkin",
    firstname: "Brad",
    lastname: "Wilkin",
    team: "Rebels",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "mattGibbon",
    title: "Matt Gibbon",
    firstname: "Matt",
    lastname: "Gibbon",
    team: "Rebels",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "vaioliniEkuasi",
    title: "Vaiolini Ekuasi",
    firstname: "Vaiolini",
    lastname: "Ekuasi",
    team: "Rebels",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "joePincus",
    title: "Joe Pincus",
    firstname: "Joe",
    lastname: "Pincus",
    team: "Rebels",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "davidFeliuai",
    title: "David Feliuai",
    firstname: "David",
    lastname: "Feliuai",
    team: "Rebels",
    position: "centre",
    positions: ["centre"],
  },
  {
    key: "nickJooste",
    title: "Nick Jooste",
    firstname: "Nick",
    lastname: "Jooste",
    team: "Rebels",
    position: "outsideBack",
    positions: ["outsideBack", "centre"],
  },
  {
    key: "jakeStrachan",
    title: "Jake Strachan",
    firstname: "Jake",
    lastname: "Strachan",
    team: "Rebels",
    position: "flyhalf",
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "lukasRipley",
    title: "Lukas Ripley",
    firstname: "Lukas",
    lastname: "Ripley",
    team: "Rebels",
    position: "centre",
    positions: ["centre", "outsideBack"],
  },
  {
    key: "angeloSmith",
    title: "Angelo Smith",
    firstname: "Angelo",
    lastname: "Smith",
    team: "Rebels",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "tuainaTaii Tualima",
    title: "Tuaina Taii Tualima",
    firstname: "Tuaina",
    lastname: "Taii Tualima",
    team: "Rebels",
    position: "lock",
    positions: ["lock", "backrow"],
  },
  {
    key: "jamesTuttle",
    title: "James Tuttle",
    firstname: "James",
    lastname: "Tuttle",
    team: "Rebels",
    position: "scrumhalf",
    positions: ["scrumhalf"],
  },
  {
    key: "danielMaiava",
    title: "Daniel Maiava",
    firstname: "Daniel",
    lastname: "Maiava",
    team: "Rebels",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "darbyLancaster",
    title: "Darby Lancaster",
    firstname: "Darby",
    lastname: "Lancaster",
    team: "Rebels",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "davidVaihu",
    title: "David Vaihu",
    firstname: "David",
    lastname: "Vaihu",
    team: "Rebels",
    position: "centre",
    positions: ["centre", "outsideBack"],
  },
  {
    key: "divadPalu",
    title: "Divad Palu",
    firstname: "Divad",
    lastname: "Palu",
    team: "Rebels",
    position: "centre",
    positions: ["centre"],
  },
  {
    key: "glenVaihu",
    title: "Glen Vaihu",
    firstname: "Glen",
    lastname: "Vaihu",
    team: "Rebels",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "jackMaunder",
    title: "Jack Maunder",
    firstname: "Jack",
    lastname: "Maunder",
    team: "Rebels",
    position: "scrumhalf",
    positions: ["scrumhalf"],
  },
  {
    key: "lebronNaea",
    title: "Lebron Naea",
    firstname: "Lebron",
    lastname: "Naea",
    team: "Rebels",
    position: "centre",
    positions: ["centre"],
  },
  {
    key: "lukhanSalakaia-Loto",
    title: "Lukhan Salakaia-Loto",
    firstname: "Lukhan",
    lastname: "Salakaia-Loto",
    team: "Rebels",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "masonGordon",
    title: "Mason Gordon",
    firstname: "Mason",
    lastname: "Gordon",
    team: "Rebels",
    position: "flyhalf",
    positions: ["flyhalf"],
  },
  {
    key: "robLeota",
    title: "Rob Leota",
    firstname: "Rob",
    lastname: "Leota",
    team: "Rebels",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "zacHough",
    title: "Zac Hough",
    firstname: "Zac",
    lastname: "Hough",
    team: "Rebels",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "isaacAedo Kailea",
    title: "Isaac Aedo Kailea",
    firstname: "Isaac",
    lastname: "Aedo Kailea",
    team: "Rebels",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "ethanDobbins",
    title: "Ethan Dobbins",
    firstname: "Ethan",
    lastname: "Dobbins",
    team: "Rebels",
    position: "hooker",
    positions: ["hooker"],
  },
  {
    key: "cabousEloff",
    title: "Cabous Eloff",
    firstname: "Cabous",
    lastname: "Eloff",
    team: "Rebels",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "poneFa'amausili",
    title: "Pone Fa'amausili",
    firstname: "Pone",
    lastname: "Fa'amausili",
    team: "Rebels",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "samTalakai",
    title: "Sam Talakai",
    firstname: "Sam",
    lastname: "Talakai",
    team: "Rebels",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "tanielaTupou",
    title: "Taniela Tupou",
    firstname: "Taniela",
    lastname: "Tupou",
    team: "Rebels",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "jordanUelese",
    title: "Jordan Uelese",
    firstname: "Jordan",
    lastname: "Uelese",
    team: "Rebels",
    position: "hooker",
    positions: ["hooker"],
  }
]