export const highlanders = [
  {
    key: "timociTavatavanawai",
    title: "Timoci Tavatavanawai",
    firstname: "Timoci",
    lastname: "Tavatavanawai",
    team: "Highlanders",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "billyHarmon",
    title: "Billy Harmon",
    firstname: "Billy",
    lastname: "Harmon",
    team: "Highlanders",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "jonaNareki",
    title: "Jona Nareki",
    firstname: "Jona",
    lastname: "Nareki",
    team: "Highlanders",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "hughRenton",
    title: "Hugh Renton",
    firstname: "Hugh",
    lastname: "Renton",
    team: "Highlanders",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "folauFakatava",
    title: "Folau Fakatava",
    firstname: "Folau",
    lastname: "Fakatava",
    team: "Highlanders",
    position: "scrumhalf",
    positions: ["scrumhalf"],
  },
  {
    key: "samGilbert",
    title: "Sam Gilbert",
    firstname: "Sam",
    lastname: "Gilbert",
    team: "Highlanders",
    position: "centre",
    positions: ["centre", "flyhalf", "outsideBack"],
  },
  {
    key: "jacobRatumaitavuki-Kneepkens",
    title: "Jacob Ratumaitavuki-Kneepkens",
    firstname: "Jacob",
    lastname: "Ratumaitavuki-Kneepkens",
    team: "Highlanders",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "tanieluTele'a",
    title: "Tanielu Tele'a",
    firstname: "Tanielu",
    lastname: "Tele'a",
    team: "Highlanders",
    position: "centre",
    positions: ["centre", "outsideBack"],
  },
  {
    key: "ethanDe Groot",
    title: "Ethan de Groot",
    firstname: "Ethan",
    lastname: "De Groot",
    team: "Highlanders",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "nikoraBroughton",
    title: "Nikora Broughton",
    firstname: "Nikora",
    lastname: "Broughton",
    team: "Highlanders",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "jonahLowe",
    title: "Jonah Lowe",
    firstname: "Jonah",
    lastname: "Lowe",
    team: "Highlanders",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "seanWithy",
    title: "Sean Withy",
    firstname: "Sean",
    lastname: "Withy",
    team: "Highlanders",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "ajayFaleafaga",
    title: "Ajay Faleafaga",
    firstname: "Ajay",
    lastname: "Faleafaga",
    team: "Highlanders",
    position: "flyhalf",
    positions: ["flyhalf"],
  },
  {
    key: "connorGarden-Bachop",
    title: "Connor Garden-Bachop",
    firstname: "Connor",
    lastname: "Garden-Bachop",
    team: "Highlanders",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "mattWhaanga",
    title: "Matt Whaanga",
    firstname: "Matt",
    lastname: "Whaanga",
    team: "Highlanders",
    position: "centre",
    positions: ["centre"],
  },
  {
    key: "joshTimu",
    title: "Josh Timu",
    firstname: "Josh",
    lastname: "Timu",
    team: "Highlanders",
    position: "centre",
    positions: ["centre", "outsideBack"],
  },
  {
    key: "martinBogado",
    title: "Martin Bogado",
    firstname: "Martin",
    lastname: "Bogado",
    team: "Highlanders",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "pari pariParkinson",
    title: "Pari Pari Parkinson",
    firstname: "Pari Pari",
    lastname: "Parkinson",
    team: "Highlanders",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "maxHicks",
    title: "Max Hicks",
    firstname: "Max",
    lastname: "Hicks",
    team: "Highlanders",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "cameronMillar",
    title: "Cameron Millar",
    firstname: "Cameron",
    lastname: "Millar",
    team: "Highlanders",
    position: "flyhalf",
    positions: ["flyhalf"],
  },
  {
    key: "jamesArscott",
    title: "James Arscott",
    firstname: "James",
    lastname: "Arscott",
    team: "Highlanders",
    position: "scrumhalf",
    positions: ["scrumhalf"],
  },
  {
    key: "willTucker",
    title: "Will Tucker",
    firstname: "Will",
    lastname: "Tucker",
    team: "Highlanders",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "mitchellDunshea",
    title: "Mitchell Dunshea",
    firstname: "Mitchell",
    lastname: "Dunshea",
    team: "Highlanders",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "fabianHolland",
    title: "Fabian Holland",
    firstname: "Fabian",
    lastname: "Holland",
    team: "Highlanders",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "nathanHastie",
    title: "Nathan Hastie",
    firstname: "Nathan",
    lastname: "Hastie",
    team: "Highlanders",
    position: "scrumhalf",
    positions: ["scrumhalf"],
  },
  {
    key: "jakeTe Hiwi",
    title: "Jake Te Hiwi",
    firstname: "Jake",
    lastname: "Te Hiwi",
    team: "Highlanders",
    position: "centre",
    positions: ["centre"],
  },
  {
    key: "haydenMichaels",
    title: "Hayden Michaels",
    firstname: "Hayden",
    lastname: "Michaels",
    team: "Highlanders",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "oliverHaig",
    title: "Oliver Haig",
    firstname: "Oliver",
    lastname: "Haig",
    team: "Highlanders",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "rhysPatchell",
    title: "Rhys Patchell",
    firstname: "Rhys",
    lastname: "Patchell",
    team: "Highlanders",
    position: "flyhalf",
    positions: ["flyhalf"],
  },
  {
    key: "tomSanders",
    title: "Tom Sanders",
    firstname: "Tom",
    lastname: "Sanders",
    team: "Highlanders",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "jermaineAinsley",
    title: "Jermaine Ainsley",
    firstname: "Jermaine",
    lastname: "Ainsley",
    team: "Highlanders",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "henryBell",
    title: "Henry Bell",
    firstname: "Henry",
    lastname: "Bell",
    team: "Highlanders",
    position: "hooker",
    positions: ["hooker"],
  },
  {
    key: "lucaInch",
    title: "Luca Inch",
    firstname: "Luca",
    lastname: "Inch",
    team: "Highlanders",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "rickyJackson",
    title: "Ricky Jackson",
    firstname: "Ricky",
    lastname: "Jackson",
    team: "Highlanders",
    position: "hooker",
    positions: ["hooker"],
  },
  {
    key: "aydenJohnstone",
    title: "Ayden Johnstone",
    firstname: "Ayden",
    lastname: "Johnstone",
    team: "Highlanders",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "danLienert-Brown",
    title: "Dan Lienert-Brown",
    firstname: "Dan",
    lastname: "Lienert-Brown",
    team: "Highlanders",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "saulaMau",
    title: "Saula Mau",
    firstname: "Saula",
    lastname: "Mau",
    team: "Highlanders",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "jackTaylor",
    title: "Jack Taylor",
    firstname: "Jack",
    lastname: "Taylor",
    team: "Highlanders",
    position: "hooker",
    positions: ["hooker"],
  }
]