export const brumbies = [
  {
    key: "tomWright",
    title: "Tom Wright",
    firstname: "Tom",
    lastname: "Wright",
    team: "Brumbies",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "lachlanLonergan",
    title: "Lachlan Lonergan",
    firstname: "Lachlan",
    lastname: "Lonergan",
    team: "Brumbies",
    position: "hooker",
    positions: ["hooker"],
  },
  {
    key: "robValetini",
    title: "Rob Valetini",
    firstname: "Rob",
    lastname: "Valetini",
    team: "Brumbies",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "coreyToole",
    title: "Corey Toole",
    firstname: "Corey",
    lastname: "Toole",
    team: "Brumbies",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "ryanLonergan",
    title: "Ryan Lonergan",
    firstname: "Ryan",
    lastname: "Lonergan",
    team: "Brumbies",
    position: "scrumhalf",
    positions: ["scrumhalf"],
  },
  {
    key: "andyMuirhead",
    title: "Andy Muirhead",
    firstname: "Andy",
    lastname: "Muirhead",
    team: "Brumbies",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "jamesSlipper",
    title: "James Slipper",
    firstname: "James",
    lastname: "Slipper",
    team: "Brumbies",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "lenIkitau",
    title: "Len Ikitau",
    firstname: "Len",
    lastname: "Ikitau",
    team: "Brumbies",
    position: "centre",
    positions: ["centre"],
  },
  {
    key: "tomHooper",
    title: "Tom Hooper",
    firstname: "Tom",
    lastname: "Hooper",
    team: "Brumbies",
    position: "backrow",
    positions: ["backrow", "lock"],
  },
  {
    key: "connalMcInerney",
    title: "Connal McInerney",
    firstname: "Connal",
    lastname: "McInerney",
    team: "Brumbies",
    position: "hooker",
    positions: ["hooker"],
  },
  {
    key: "nickFrost",
    title: "Nick Frost",
    firstname: "Nick",
    lastname: "Frost",
    team: "Brumbies",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "noahLolesio",
    title: "Noah Lolesio",
    firstname: "Noah",
    lastname: "Lolesio",
    team: "Brumbies",
    position: "flyhalf",
    positions: ["flyhalf"],
  },
  {
    key: "tamatiTua",
    title: "Tamati Tua",
    firstname: "Tamati",
    lastname: "Tua",
    team: "Brumbies",
    position: "centre",
    positions: ["centre"],
  },
  {
    key: "ollieSapsford",
    title: "Ollie Sapsford",
    firstname: "Ollie",
    lastname: "Sapsford",
    team: "Brumbies",
    position: "centre",
    positions: ["centre"],
  },
  {
    key: "benO'Donnell",
    title: "Ben O'Donnell",
    firstname: "Ben",
    lastname: "O'Donnell",
    team: "Brumbies",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "lukeReimer",
    title: "Luke Reimer",
    firstname: "Luke",
    lastname: "Reimer",
    team: "Brumbies",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "jackDebreczeni",
    title: "Jack Debreczeni",
    firstname: "Jack",
    lastname: "Debreczeni",
    team: "Brumbies",
    position: "flyhalf",
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "roryScott",
    title: "Rory Scott",
    firstname: "Rory",
    lastname: "Scott",
    team: "Brumbies",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "cadeyrnNeville",
    title: "Cadeyrn Neville",
    firstname: "Cadeyrn",
    lastname: "Neville",
    team: "Brumbies",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "jahromeBrown",
    title: "Jahrome Brown",
    firstname: "Jahrome",
    lastname: "Brown",
    team: "Brumbies",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "charlieCale",
    title: "Charlie Cale",
    firstname: "Charlie",
    lastname: "Cale",
    team: "Brumbies",
    position: "lock",
    positions: ["lock", "backrow"],
  },
  {
    key: "darcySwain",
    title: "Darcy Swain",
    firstname: "Darcy",
    lastname: "Swain",
    team: "Brumbies",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "harrisonGoddard",
    title: "Harrison Goddard",
    firstname: "Harrison",
    lastname: "Goddard",
    team: "Brumbies",
    position: "scrumhalf",
    positions: ["scrumhalf"],
  },
  {
    key: "hudsonCreighton",
    title: "Hudson Creighton",
    firstname: "Hudson",
    lastname: "Creighton",
    team: "Brumbies",
    position: "centre",
    positions: ["centre"],
  },
  {
    key: "austinAnderson",
    title: "Austin Anderson",
    firstname: "Austin",
    lastname: "Anderson",
    team: "Brumbies",
    position: "centre",
    positions: ["centre"],
  },
  {
    key: "declanMeredith",
    title: "Declan Meredith",
    firstname: "Declan",
    lastname: "Meredith",
    team: "Brumbies",
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: "edKennedy",
    title: "Ed Kennedy",
    firstname: "Ed",
    lastname: "Kennedy",
    team: "Brumbies",
    position: "backrow",
    positions: ["backrow"],
  },
  {
    key: "klaytonThorn",
    title: "Klayton Thorn",
    firstname: "Klayton",
    lastname: "Thorn",
    team: "Brumbies",
    position: "scrumhalf",
    positions: ["scrumhalf"],
  },
  {
    key: "lachlanShaw",
    title: "Lachlan Shaw",
    firstname: "Lachlan",
    lastname: "Shaw",
    team: "Brumbies",
    position: "lock",
    positions: ["lock"],
  },
  {
    key: "allanAlaalatoa",
    title: "Allan Alaalatoa",
    firstname: "Allan",
    lastname: "Alaalatoa",
    team: "Brumbies",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "fredKaihea",
    title: "Fred Kaihea",
    firstname: "Fred",
    lastname: "Kaihea",
    team: "Brumbies",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "sefoKautai",
    title: "Sefo Kautai",
    firstname: "Sefo",
    lastname: "Kautai",
    team: "Brumbies",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "billyPollard",
    title: "Billy Pollard",
    firstname: "Billy",
    lastname: "Pollard",
    team: "Brumbies",
    position: "hooker",
    positions: ["hooker"],
  },
  {
    key: "blakeSchoupp",
    title: "Blake Schoupp",
    firstname: "Blake",
    lastname: "Schoupp",
    team: "Brumbies",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "rhysVan Nek",
    title: "Rhys Van Nek",
    firstname: "Rhys",
    lastname: "Van Nek",
    team: "Brumbies",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: "harryVella",
    title: "Harry Vella",
    firstname: "Harry",
    lastname: "Vella",
    team: "Brumbies",
    position: "prop",
    positions: ["prop"],
  }
]