export const wallabiesPlayers = [
  {
    key: 'andrewKellaway',
    title: 'Andrew Kellaway',
    firstname: 'Andrew',
    lastname: 'Kellaway',
    positions: ["outsideBack"],
    teams: ["rebels", "wallabies"],
  },
  {
    key: 'angusBell',
    title: 'Angus Bell',
    firstname: 'Angus',
    lastname: 'Bell',
    positions: ["prop"],
    teams: ["waratahs", "wallabies"],
  },
  {
    key: 'benDonaldson',
    title: 'Ben Donaldson',
    firstname: 'Ben',
    lastname: 'Donaldson',
    positions: ["flyhalf", "outsideBack"],
    teams: ["force", "wallabies"],
  },
  {
    key: 'blakeSchoupp',
    title: 'Blake Schoupp',
    firstname: 'Blake',
    lastname: 'Schoupp',
    positions: ["prop"],
    teams: ["brumbies", "wallabies"],
  },
  {
    key: 'carterGordon',
    title: 'Carter Gordon',
    firstname: 'Carter',
    lastname: 'Gordon',
    positions: ["flyhalf"],
    teams: ["rebels", "wallabies"],
  },
  {
    key: 'davidPorecki',
    title: 'David Porecki',
    firstname: 'David',
    lastname: 'Porecki',
    positions: ["hooker"],
    teams: ["waratahs", "wallabies"],
  },
  {
    key: 'fraserMcreight',
    title: 'Fraser McReight',
    firstname: 'Fraser',
    lastname: 'McReight',
    positions: ["backrow"],
    teams: ["reds", "wallabies"],
  },
  {
    key: 'issakFinesLeleiwasa',
    title: 'Issak Fines-Leleiwasa',
    firstname: 'Issak',
    lastname: 'Fines-Leleiwasa',
    positions: ["scrumhalf"],
    teams: ["force", "wallabies"],
  },
  {
    key: 'izaiaPerese',
    title: 'Izaia Perese',
    firstname: 'Izaia',
    lastname: 'Perese',
    positions: ["centre", "outsideBack"],
    teams: ["waratahs", "wallabies"],
  },
  {
    key: 'jamesSlipper',
    title: 'James Slipper',
    firstname: 'James',
    lastname: 'Slipper',
    positions: ["prop"],
    teams: ["brumbies", "wallabies"],
  },
  {
    key: 'jordanPetaia',
    title: 'Jordan Petaia',
    firstname: 'Jordan',
    lastname: 'Petaia',
    positions: ["outsideBack", "centre"],
    teams: ["reds", "wallabies"],
  },
  {
    key: 'jordanUelese',
    title: 'Jordan Uelese',
    firstname: 'Jordan',
    lastname: 'Uelese',
    positions: ["hooker"],
    teams: ["wallabies"],
  },
  {
    key: 'joshKemeny',
    title: 'Josh Kemeny',
    firstname: 'Josh',
    lastname: 'Kemeny',
    positions: ["backrow"],
    teams: ["rebels", "wallabies"],
  },
  {
    key: 'lalakaiFoketi',
    title: 'Lalakai Foketi',
    firstname: 'Lalakai',
    lastname: 'Foketi',
    positions: ["centre"],
    teams: ["waratahs", "wallabies"],
  },
  {
    key: 'langiGleeson',
    title: 'Langi Gleeson',
    firstname: 'Langi',
    lastname: 'Gleeson',
    positions: ["backrow"],
    teams: ["waratahs", "wallabies"],
  },
  {
    key: 'marikaKoroibete',
    title: 'Marika Koroibete',
    firstname: 'Marika',
    lastname: 'Koroibete',
    positions: ["outsideBack"],
    teams: ["wallabies"],
  },
  {
    key: 'markNawaqanitawase',
    title: 'Mark Nawaqanitawase',
    firstname: 'Mark',
    lastname: 'Nawaqanitawase',
    positions: ["outsideBack"],
    teams: ["waratahs", "wallabies"],
  },
  {
    key: 'mattFaessler',
    title: 'Matt Faessler',
    firstname: 'Matt',
    lastname: 'Faessler',
    positions: ["hooker"],
    teams: ["reds", "wallabies"],
  },
  {
    key: 'mattPhilip',
    title: 'Matt Philip',
    firstname: 'Matt',
    lastname: 'Philip',
    positions: ["lock"],
    teams: ["wallabies"],
  },
  {
    key: 'maxJorgensen',
    title: 'Max Jorgensen',
    firstname: 'Max',
    lastname: 'Jorgensen',
    positions: ["outsideBack"],
    teams: ["waratahs", "wallabies"],
  },
  {
    key: 'nicWhite',
    title: 'Nic White',
    firstname: 'Nic',
    lastname: 'White',
    positions: ["outsideBack"],
    teams: ["force", "wallabies"],
  },
  {
    key: 'nickFrost',
    title: 'Nick Frost',
    firstname: 'Nick',
    lastname: 'Frost',
    positions: ["lock"],
    teams: ["brumbies", "wallabies"],
  },
  {
    key: 'poneFaamausili',
    title: "Pone Fa'amausili",
    firstname: 'Pone',
    lastname: "Fa'amausili",
    positions: ["prop"],
    teams: ["rebels", "wallabies"],
  },
  {
    key: 'richieArnold',
    title: 'Richie Arnold',
    firstname: 'Richie',
    lastname: 'Arnold',
    positions: ["lock"],
    teams: ["wallabies"],
  },
  {
    key: 'robLeota',
    title: 'Rob Leota',
    firstname: 'Rob',
    lastname: 'Leota',
    positions: ["backrow", "lock"],
    teams: ["rebels", "wallabies"],
  },
  {
    key: 'robValetini',
    title: 'Rob Valetini',
    firstname: 'Rob',
    lastname: 'Valetini',
    positions: ["backrow"],
    teams: ["brumbies", "wallabies"],
  },
  {
    key: 'samuKerevi',
    title: 'Samu Kerevi',
    firstname: 'Samu',
    lastname: 'Kerevi',
    positions: ["centre"],
    teams: ["wallabies"],
  },
  {
    key: 'suliasiVunivalu',
    title: 'Suliasi Vunivalu',
    firstname: 'Suliasi',
    lastname: 'Vunivalu',
    positions: ["outsideBack"],
    teams: ["reds", "wallabies"],
  },
  {
    key: 'tanielaTupou',
    title: 'Taniela Tupou',
    firstname: 'Taniela',
    lastname: 'Tupou',
    positions: ["outsideBack"],
    teams: ["rebels", "wallabies"],
  },
  {
    key: 'tateMcdermott',
    title: 'Tate McDermott',
    firstname: 'Tate',
    lastname: 'McDermott',
    positions: ["scrumhalf"],
    teams: ["reds", "wallabies"],
  },
  {
    key: 'tomHooper',
    title: 'Tom Hooper',
    firstname: 'Tom',
    lastname: 'Hooper',
    positions: ["backrow", "lock"],
    teams: ["brumbies", "wallabies"],
  },
  {
    key: 'willSkelton',
    title: 'Will Skelton',
    firstname: 'Will',
    lastname: 'Skelton',
    positions: ["lock"],
    teams: ["wallabies"],
  },
  {
    key: 'zaneNonggorr',
    title: 'Zane Nonggorr',
    firstname: 'Zane',
    lastname: 'Nonggorr',
    positions: ["prop"],
    teams: ["reds", "wallabies"],
  },
  {
    key: 'michaelHooper',
    title: 'Michael Hooper',
    firstname: 'Michael',
    lastname: 'Hooper',
    positions: ["backrow"],
    teams: ["wallabies"],
  },
  {
    key: "lachlanLonergan",
    title: "Lachlan Lonergan",
    firstname: "Lachlan",
    lastname: "Lonergan",
    teams: ["brumbies", "wallabies"],
    positions: ["hooker"],
  },
  {
    key: "jamesSlipper",
    title: "James Slipper",
    firstname: "James",
    lastname: "Slipper",
    teams: ["brumbies", "wallabies"],
    positions: ["prop"],
  },
  {
    key: "noahLolesio",
    title: "Noah Lolesio",
    firstname: "Noah",
    lastname: "Lolesio",
    teams: ["brumbies", "wallabies"],
    positions: ["flyhalf"],
  },
  {
    key: "allanAlaalatoa",
    title: "Allan Alaalatoa",
    firstname: "Allan",
    lastname: "Alaalatoa",
    teams: ["brumbies", "wallabies"],
    positions: ["prop"],
  },
  {
    key: "izackRodda",
    title: "Izack Rodda",
    firstname: "Izack",
    lastname: "Rodda",
    teams: ["force", "wallabies"],
    positions: ["lock"],
  },
  {
    key: "filipoDaugunu",
    title: "Filipo Daugunu",
    firstname: "Filipo",
    lastname: "Daugunu",
    teams: ["rebels", "wallabies"],
    positions: ["outsideBack", "centre"],
  },
  {
    key: "bradWilkin",
    title: "Brad Wilkin",
    firstname: "Brad",
    lastname: "Wilkin",
    teams: ["rebels", "wallabies"],
    positions: ["backrow"],
  },
  {
    key: "mattGibbon",
    title: "Matt Gibbon",
    firstname: "Matt",
    lastname: "Gibbon",
    teams: ["rebels", "wallabies"],
    positions: ["prop"],
  },
  {
    key: "lukhanSalakaia-Loto",
    title: "Lukhan Salakaia-Loto",
    firstname: "Lukhan",
    lastname: "Salakaia-Loto",
    teams: ["rebels", "wallabies"],
    positions: ["lock"],
  },
  {
    key: "harryWilson",
    title: "Harry Wilson",
    firstname: "Harry",
    lastname: "Wilson",
    teams: ["reds", "wallabies"],
    positions: ["backrow"],
  },
  {
    key: "jamesO'Connor",
    title: "James O'Connor",
    firstname: "James",
    lastname: "O'Connor",
    teams: ["reds", "wallabies"],
    positions: ["flyhalf", "centre"],
  },
  {
    key: "hunterPaisami",
    title: "Hunter Paisami",
    firstname: "Hunter",
    lastname: "Paisami",
    teams: ["reds", "wallabies"],
    positions: ["centre"],
  },
  {
    key: "harryJohnson-Holmes",
    title: "Harry Johnson-Holmes",
    firstname: "Harry",
    lastname: "Johnson-Holmes",
    teams: ["waratahs", "wallabies"],
    positions: ["prop"],
  },
  {
    key: "jedHolloway",
    title: "Jed Holloway",
    firstname: "Jed",
    lastname: "Holloway",
    teams: ["waratahs", "wallabies"],
    positions: ["lock", "backrow"],
  },
  {
    key: "jakeGordon",
    title: "Jake Gordon",
    firstname: "Jake",
    lastname: "Gordon",
    teams: ["waratahs", "wallabies"],
    positions: ["scrumhalf"],
  }
]