export const wallabiesPlayers = [
  {
    key: 'andrewKellaway',
    title: 'Andrew Kellaway',
    firstname: 'Andrew',
    lastname: 'Kellaway',
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: 'angusBell',
    title: 'Angus Bell',
    firstname: 'Angus',
    lastname: 'Bell',
    position: "prop",
    positions: ["prop"],
  },
  {
    key: 'benDonaldson',
    title: 'Ben Donaldson',
    firstname: 'Ben',
    lastname: 'Donaldson',
    position: "flyhalf",
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: 'blakeSchoupp',
    title: 'Blake Schoupp',
    firstname: 'Blake',
    lastname: 'Schoupp',
    position: "prop",
    positions: ["prop"],
  },
  {
    key: 'carterGordon',
    title: 'Carter Gordon',
    firstname: 'Carter',
    lastname: 'Gordon',
    position: "flyhalf",
    positions: ["flyhalf"],
  },
  {
    key: 'davidPorecki',
    title: 'David Porecki',
    firstname: 'David',
    lastname: 'Porecki',
    position: "hooker",
    positions: ["hooker"],
  },
  {
    key: 'fraserMcreight',
    title: 'Fraser McReight',
    firstname: 'Fraser',
    lastname: 'McReight',
    position: "backRow",
    positions: ["backRow"],
  },
  {
    key: 'issakFinesLeleiwasa',
    title: 'Issak Fines-Leleiwasa',
    firstname: 'Issak',
    lastname: 'Fines-Leleiwasa',
    position: "scrumhalf",
    positions: ["scrumhalf"],
  },
  {
    key: 'izaiaPerese',
    title: 'Izaia Perese',
    firstname: 'Izaia',
    lastname: 'Perese',
    position: "centre",
    positions: ["centre", "outsideBack"],
  },
  {
    key: 'jamesSlipper',
    title: 'James Slipper',
    firstname: 'James',
    lastname: 'Slipper',
    position: "prop",
    positions: ["prop"],
  },
  {
    key: 'jordanPetaia',
    title: 'Jordan Petaia',
    firstname: 'Jordan',
    lastname: 'Petaia',
    position: "outsideBack",
    positions: ["outsideBack", "centre"],
  },
  {
    key: 'jordanUelese',
    title: 'Jordan Uelese',
    firstname: 'Jordan',
    lastname: 'Uelese',
    position: "hooker",
    positions: ["hooker"],
  },
  {
    key: 'joshKemeny',
    title: 'Josh Kemeny',
    firstname: 'Josh',
    lastname: 'Kemeny',
    position: "backRow",
    positions: ["backRow"],
  },
  {
    key: 'lalakaiFoketi',
    title: 'Lalakai Foketi',
    firstname: 'Lalakai',
    lastname: 'Foketi',
    position: "centre",
    positions: ["centre"],
  },
  {
    key: 'langiGleeson',
    title: 'Langi Gleeson',
    firstname: 'Langi',
    lastname: 'Gleeson',
    position: "backRow",
    positions: ["backRow"],
  },
  {
    key: 'marikaKoroibete',
    title: 'Marika Koroibete',
    firstname: 'Marika',
    lastname: 'Koroibete',
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: 'markNawaqanitawase',
    title: 'Mark Nawaqanitawase',
    firstname: 'Mark',
    lastname: 'Nawaqanitawase',
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: 'mattFaessler',
    title: 'Matt Faessler',
    firstname: 'Matt',
    lastname: 'Faessler',
    position: "hooker",
    positions: ["hooker"],
  },
  {
    key: 'mattPhilip',
    title: 'Matt Philip',
    firstname: 'Matt',
    lastname: 'Philip',
    position: "lock",
    positions: ["lock"],
  },
  {
    key: 'maxJorgensen',
    title: 'Max Jorgensen',
    firstname: 'Max',
    lastname: 'Jorgensen',
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: 'nicWhite',
    title: 'Nic White',
    firstname: 'Nic',
    lastname: 'White',
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: 'nickFrost',
    title: 'Nick Frost',
    firstname: 'Nick',
    lastname: 'Frost',
    position: "lock",
    positions: ["lock"],
  },
  {
    key: 'poneFaamausili',
    title: "Pone Fa'amausili",
    firstname: 'Pone',
    lastname: "Fa'amausili",
    position: "prop",
    positions: ["prop"],
  },
  {
    key: 'richieArnold',
    title: 'Richie Arnold',
    firstname: 'Richie',
    lastname: 'Arnold',
    position: "lock",
    positions: ["lock"],
  },
  {
    key: 'robLeota',
    title: 'Rob Leota',
    firstname: 'Rob',
    lastname: 'Leota',
    position: "backRow",
    positions: ["backRow", "lock"],
  },
  {
    key: 'robValetini',
    title: 'Rob Valetini',
    firstname: 'Rob',
    lastname: 'Valetini',
    position: "backRow",
    positions: ["backRow"],
  },
  {
    key: 'samuKerevi',
    title: 'Samu Kerevi',
    firstname: 'Samu',
    lastname: 'Kerevi',
    position: "centre",
    positions: ["centre"],
  },
  {
    key: 'suliasiVunivalu',
    title: 'Suliasi Vunivalu',
    firstname: 'Suliasi',
    lastname: 'Vunivalu',
    position: "outsideBack",
    positions: ["outsideBack"],
  },
  {
    key: 'tanielaTupou',
    title: 'Taniela Tupou',
    firstname: 'Taniela',
    lastname: 'Tupou',
    position: "prop",
    positions: ["outsideBack"],
  },
  {
    key: 'tateMcdermott',
    title: 'Tate McDermott',
    firstname: 'Tate',
    lastname: 'McDermott',
    position: "scrumhalf",
    positions: ["scrumhalf"],
  },
  {
    key: 'tomHooper',
    title: 'Tom Hooper',
    firstname: 'Tom',
    lastname: 'Hooper',
    position: "backRow",
    positions: ["backRow", "lock"],
  },
  {
    key: 'willSkelton',
    title: 'Will Skelton',
    firstname: 'Will',
    lastname: 'Skelton',
    position: "lock",
    positions: ["lock"],
  },
  {
    key: 'zaneNonggorr',
    title: 'Zane Nonggorr',
    firstname: 'Zane',
    lastname: 'Nonggorr',
    position: "prop",
    positions: ["prop"],
  },
  {
    key: 'michaelHooper',
    title: 'Michael Hooper',
    firstname: 'Michael',
    lastname: 'Hooper',
    position: "backRow",
    positions: ["backRow"],
  },
]