export const crusaders = [
  {
    key: "willJordan",
    title: "Will Jordan",
    firstname: "Will",
    lastname: "Jordan",
    teams: ["crusaders", "allBlacks"],
    positions: ["outsideBack"],
  },
  {
    key: "leviAumua",
    title: "Levi Aumua",
    firstname: "Levi",
    lastname: "Aumua",
    teams: ["crusaders"],
    positions: ["centre"],
  },
  {
    key: "davidHavili",
    title: "David Havili",
    firstname: "David",
    lastname: "Havili",
    teams: ["crusaders", "allBlacks"],
    positions: ["centre", "flyhalf", "outsideBack"],
  },
  {
    key: "maccaSpringer",
    title: "Macca Springer",
    firstname: "Macca",
    lastname: "Springer",
    teams: ["crusaders"],
    positions: ["outsideBack"],
  },
  {
    key: "sevuReece",
    title: "Sevu Reece",
    firstname: "Sevu",
    lastname: "Reece",
    teams: ["crusaders", "allBlacks"],
    positions: ["outsideBack"],
  },
  {
    key: "ethanBlackadder",
    title: "Ethan Blackadder",
    firstname: "Ethan",
    lastname: "Blackadder",
    teams: ["crusaders", "allBlacks"],
    positions: ["backrow"],
  },
  {
    key: "rivezReihana",
    title: "Rivez Reihana",
    firstname: "Rivez",
    lastname: "Reihana",
    teams: ["crusaders"],
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "georgeBell",
    title: "George Bell",
    firstname: "George",
    lastname: "Bell",
    teams: ["crusaders"],
    positions: ["hooker"],
  },
  {
    key: "brodieMcAlister",
    title: "Brodie McAlister",
    firstname: "Brodie",
    lastname: "McAlister",
    teams: ["crusaders"],
    positions: ["hooker"],
  },
  {
    key: "scottBarrett",
    title: "Scott Barrett",
    firstname: "Scott",
    lastname: "Barrett",
    teams: ["crusaders", "allBlacks"],
    positions: ["lock", "backrow"],
  },
  {
    key: "noahHotham",
    title: "Noah Hotham",
    firstname: "Noah",
    lastname: "Hotham",
    teams: ["crusaders"],
    positions: ["scrumhalf"],
  },
  {
    key: "dallasMcLeod",
    title: "Dallas McLeod",
    firstname: "Dallas",
    lastname: "McLeod",
    teams: ["crusaders"],
    positions: ["centre", "outsideBack"],
  },
  {
    key: "codieTaylor",
    title: "Codie Taylor",
    firstname: "Codie",
    lastname: "Taylor",
    teams: ["crusaders", "allBlacks"],
    positions: ["hooker"],
  },
  {
    key: "manasaMataele",
    title: "Manasa Mataele",
    firstname: "Manasa",
    lastname: "Mataele",
    teams: ["crusaders"],
    positions: ["outsideBack"],
  },
  {
    key: "heremaiaMurray",
    title: "Heremaia Murray",
    firstname: "Heremaia",
    lastname: "Murray",
    teams: ["crusaders"],
    positions: ["outsideBack"],
  },
  {
    key: "christianLio-Willie",
    title: "Christian Lio-Willie",
    firstname: "Christian",
    lastname: "Lio-Willie",
    teams: ["crusaders"],
    positions: ["backrow"],
  },
  {
    key: "tahaKemara",
    title: "Taha Kemara",
    firstname: "Taha",
    lastname: "Kemara",
    teams: ["crusaders"],
    positions: ["flyhalf"],
  },
  {
    key: "tomChristie",
    title: "Tom Christie",
    firstname: "Tom",
    lastname: "Christie",
    teams: ["crusaders"],
    positions: ["backrow"],
  },
  {
    key: "jamieHannah",
    title: "Jamie Hannah",
    firstname: "Jamie",
    lastname: "Hannah",
    teams: ["crusaders"],
    positions: ["lock"],
  },
  {
    key: "chayFihaki",
    title: "Chay Fihaki",
    firstname: "Chay",
    lastname: "Fihaki",
    teams: ["crusaders"],
    positions: ["outsideBack"],
  },
  {
    key: "williHeinz",
    title: "Willi Heinz",
    firstname: "Willi",
    lastname: "Heinz",
    teams: ["crusaders"],
    positions: ["scrumhalf"],
  },
  {
    key: "domGardiner",
    title: "Dom Gardiner",
    firstname: "Dom",
    lastname: "Gardiner",
    teams: ["crusaders"],
    positions: ["backrow"],
  },
  {
    key: "mitchellDrummond",
    title: "Mitchell Drummond",
    firstname: "Mitchell",
    lastname: "Drummond",
    teams: ["crusaders"],
    positions: ["scrumhalf"],
  },
  {
    key: "cullenGrace",
    title: "Cullen Grace",
    firstname: "Cullen",
    lastname: "Grace",
    teams: ["crusaders"],
    positions: ["backrow"],
  },
  {
    key: "zachGallagher",
    title: "Zach Gallagher",
    firstname: "Zach",
    lastname: "Gallagher",
    teams: ["crusaders"],
    positions: ["lock"],
  },
  {
    key: "quintenStrange",
    title: "Quinten Strange",
    firstname: "Quinten",
    lastname: "Strange",
    teams: ["crusaders"],
    positions: ["lock"],
  },
  {
    key: "fergusBurke",
    title: "Fergus Burke",
    firstname: "Fergus",
    lastname: "Burke",
    teams: ["crusaders"],
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "andrewTurner",
    title: "Andrew Turner",
    firstname: "Andrew",
    lastname: "Turner",
    teams: ["crusaders"],
    positions: ["lock"],
  },
  {
    key: "joneRova",
    title: "Jone Rova",
    firstname: "Jone",
    lastname: "Rova",
    teams: ["crusaders"],
    positions: ["centre"],
  },
  {
    key: "leighHalfpenny",
    title: "Leigh Halfpenny",
    firstname: "Leigh",
    lastname: "Halfpenny",
    teams: ["crusaders"],
    positions: ["outsideBack"],
  },
  {
    key: "ryanCrotty",
    title: "Ryan Crotty",
    firstname: "Ryan",
    lastname: "Crotty",
    teams: ["crusaders"],
    positions: ["centre"],
  },
  {
    key: "tahlorCahill",
    title: "Tahlor Cahill",
    firstname: "Tahlor",
    lastname: "Cahill",
    teams: ["crusaders"],
    positions: ["lock"],
  },
  {
    key: "coreyKellow",
    title: "Corey Kellow",
    firstname: "Corey",
    lastname: "Kellow",
    teams: ["crusaders"],
    positions: ["backrow"],
  },
  {
    key: "georgeBower",
    title: "George Bower",
    firstname: "George",
    lastname: "Bower",
    teams: ["crusaders"],
    positions: ["prop"],
  },
  {
    key: "finlayBrewis",
    title: "Finlay Brewis",
    firstname: "Finlay",
    lastname: "Brewis",
    teams: ["crusaders"],
    positions: ["prop"],
  },
  {
    key: "owenFranks",
    title: "Owen Franks",
    firstname: "Owen",
    lastname: "Franks",
    teams: ["crusaders"],
    positions: ["prop"],
  },
  {
    key: "ioaneMoananu",
    title: "Ioane Moananu",
    firstname: "Ioane",
    lastname: "Moananu",
    teams: ["crusaders"],
    positions: ["hooker"],
  },
  {
    key: "joeMoody",
    title: "Joe Moody",
    firstname: "Joe",
    lastname: "Moody",
    teams: ["crusaders"],
    positions: ["prop"],
  },
  {
    key: "fletcherNewell",
    title: "Fletcher Newell",
    firstname: "Fletcher",
    lastname: "Newell",
    teams: ["crusaders", "allBlacks"],
    positions: ["prop"],
  },
  {
    key: "tamaitiWilliams",
    title: "Tamaiti Williams",
    firstname: "Tamaiti",
    lastname: "Williams",
    teams: ["crusaders", "allBlacks"],
    positions: ["prop"],
  }
]