export const blues = [
  {
    key: "markTelea",
    title: "Mark Telea",
    firstname: "Mark",
    lastname: "Telea",
    teams: ["blues", "allBlacks"],
    positions: ["outsideBack"],
  },
  {
    key: "hoskinsSotutu",
    title: "Hoskins Sotutu",
    firstname: "Hoskins",
    lastname: "Sotutu",
    teams: ["blues", "allBlacks"],
    positions: ["backrow"],
  },
  {
    key: "stephenPerofeta",
    title: "Stephen Perofeta",
    firstname: "Stephen",
    lastname: "Perofeta",
    teams: ["blues", "allBlacks"],
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "calebClarke",
    title: "Caleb Clarke",
    firstname: "Caleb",
    lastname: "Clarke",
    teams: ["blues", "allBlacks"],
    positions: ["outsideBack"],
  },
  {
    key: "rickyRiccitelli",
    title: "Ricky Riccitelli",
    firstname: "Ricky",
    lastname: "Riccitelli",
    teams: ["blues"],
    positions: ["hooker"],
  },
  {
    key: "riekoIoane",
    title: "Rieko Ioane",
    firstname: "Rieko",
    lastname: "Ioane",
    teams: ["blues", "allBlacks"],
    positions: ["centre", "outsideBack"],
  },
  {
    key: "coreyEvans",
    title: "Corey Evans",
    firstname: "Corey",
    lastname: "Evans",
    teams: ["blues"],
    positions: ["centre"],
  },
  {
    key: "daltonPapali'i",
    title: "Dalton Papali'i",
    firstname: "Dalton",
    lastname: "Papali'i",
    teams: ["blues", "allBlacks"],
    positions: ["backrow"],
  },
  {
    key: "finlayChristie",
    title: "Finlay Christie",
    firstname: "Finlay",
    lastname: "Christie",
    teams: ["blues", "allBlacks"],
    positions: ["scrumhalf"],
  },
  {
    key: "harryPlummer",
    title: "Harry Plummer",
    firstname: "Harry",
    lastname: "Plummer",
    teams: ["blues"],
    positions: ["centre", "flyhalf"],
  },
  {
    key: "zarnSullivan",
    title: "Zarn Sullivan",
    firstname: "Zarn",
    lastname: "Sullivan",
    teams: ["blues"],
    positions: ["outsideBack"],
  },
  {
    key: "bryceHeem",
    title: "Bryce Heem",
    firstname: "Bryce",
    lastname: "Heem",
    teams: ["blues"],
    positions: ["centre", "outsideBack"],
  },
  {
    key: "cameronSuafoa",
    title: "Cameron Suafoa",
    firstname: "Cameron",
    lastname: "Suafoa",
    teams: ["blues"],
    positions: ["backrow", "lock"],
  },
  {
    key: "antonSegner",
    title: "Anton Segner",
    firstname: "Anton",
    lastname: "Segner",
    teams: ["blues"],
    positions: ["backrow"],
  },
  {
    key: "adrianChoat",
    title: "Adrian Choat",
    firstname: "Adrian",
    lastname: "Choat",
    teams: ["blues"],
    positions: ["backrow"],
  },
  {
    key: "ajLam",
    title: "AJ Lam",
    firstname: "AJ",
    lastname: "Lam",
    teams: ["blues"],
    positions: ["outsideBack", "centre"],
  },
  {
    key: "akiraIoane",
    title: "Akira Ioane",
    firstname: "Akira",
    lastname: "Ioane",
    teams: ["blues", "allBlacks"],
    positions: ["backrow"],
  },
  {
    key: "samDarry",
    title: "Sam Darry",
    firstname: "Sam",
    lastname: "Darry",
    teams: ["blues"],
    positions: ["lock"],
  },
  {
    key: "taufaFunaki",
    title: "Taufa Funaki",
    firstname: "Taufa",
    lastname: "Funaki",
    teams: ["blues"],
    positions: ["scrumhalf"],
  },
  {
    key: "samNock",
    title: "Sam Nock",
    firstname: "Sam",
    lastname: "Nock",
    teams: ["blues"],
    positions: ["scrumhalf"],
  },
  {
    key: "laghlanMcWhannell",
    title: "Laghlan McWhannell",
    firstname: "Laghlan",
    lastname: "McWhannell",
    teams: ["blues"],
    positions: ["lock"],
  },
  {
    key: "calebTangitau",
    title: "Caleb Tangitau",
    firstname: "Caleb",
    lastname: "Tangitau",
    teams: ["blues"],
    positions: ["outsideBack"],
  },
  {
    key: "robRush",
    title: "Rob Rush",
    firstname: "Rob",
    lastname: "Rush",
    teams: ["blues"],
    positions: ["backrow"],
  },
  {
    key: "coleForbes",
    title: "Cole Forbes",
    firstname: "Cole",
    lastname: "Forbes",
    teams: ["blues"],
    positions: ["outsideBack"],
  },
  {
    key: "jamesThompson",
    title: "James Thompson",
    firstname: "James",
    lastname: "Thompson",
    teams: ["blues"],
    positions: ["backrow"],
  },
  {
    key: "joshBeehre",
    title: "Josh Beehre",
    firstname: "Josh",
    lastname: "Beehre",
    teams: ["blues"],
    positions: ["lock"],
  },
  {
    key: "kadeBanks",
    title: "Kade Banks",
    firstname: "Kade",
    lastname: "Banks",
    teams: ["blues"],
    positions: ["outsideBack"],
  },
  {
    key: "lucasCashmore",
    title: "Lucas Cashmore",
    firstname: "Lucas",
    lastname: "Cashmore",
    teams: ["blues"],
    positions: ["flyhalf"],
  },
  {
    key: "meihanaGrindlay",
    title: "Meihana Grindlay",
    firstname: "Meihana",
    lastname: "Grindlay",
    teams: ["blues"],
    positions: ["centre"],
  },
  {
    key: "kurtEklund",
    title: "Kurt Eklund",
    firstname: "Kurt",
    lastname: "Eklund",
    teams: ["blues"],
    positions: ["hooker"],
  },
  {
    key: "joshFusitua",
    title: "Josh Fusitua",
    firstname: "Josh",
    lastname: "Fusitua",
    teams: ["blues"],
    positions: ["prop"],
  },
  {
    key: "jordanLay",
    title: "Jordan Lay",
    firstname: "Jordan",
    lastname: "Lay",
    teams: ["blues"],
    positions: ["prop"],
  },
  {
    key: "marcelRenata",
    title: "Marcel Renata",
    firstname: "Marcel",
    lastname: "Renata",
    teams: ["blues"],
    positions: ["prop"],
  },
  {
    key: "pjSheck",
    title: "PJ Sheck",
    firstname: "PJ",
    lastname: "Sheck",
    teams: ["blues"],
    positions: ["prop"],
  },
  {
    key: "angusTa'avao",
    title: "Angus Ta'avao",
    firstname: "Angus",
    lastname: "Ta'avao",
    teams: ["blues", "allBlacks"],
    positions: ["prop"],
  },
  {
    key: "ofaTu'ungafasi",
    title: "Ofa Tu'ungafasi",
    firstname: "Ofa",
    lastname: "Tu'ungafasi",
    teams: ["blues", "allBlacks"],
    positions: ["prop"],
  },
  {
    key: "soaneVikena",
    title: "Soane Vikena",
    firstname: "Soane",
    lastname: "Vikena",
    teams: ["blues"],
    positions: ["hooker"],
  },
  {
    key: "patrickTuipulotu",
    title: "Patrick Tuipulotu",
    firstname: "Patrick",
    lastname: "Tuipulotu",
    teams: ["blues", "allBlacks"],
    positions: ["lock"],
  }
]