export const reds = [
  {
    key: "mattFaessler",
    title: "Matt Faessler",
    firstname: "Matt",
    lastname: "Faessler",
    teams: ["reds", "wallabies"],
    positions: ["hooker"],
  },
  {
    key: "harryWilson",
    title: "Harry Wilson",
    firstname: "Harry",
    lastname: "Wilson",
    teams: ["reds", "wallabies"],
    positions: ["backrow"],
  },
  {
    key: "jordanPetaia",
    title: "Jordan Petaia",
    firstname: "Jordan",
    lastname: "Petaia",
    teams: ["reds", "wallabies"],
    positions: ["outsideBack", "centre"],
  },
  {
    key: "tateMcDermott",
    title: "Tate McDermott",
    firstname: "Tate",
    lastname: "McDermott",
    teams: ["reds", "wallabies"],
    positions: ["scrumhalf"],
  },
  {
    key: "fraserMcReight",
    title: "Fraser McReight",
    firstname: "Fraser",
    lastname: "McReight",
    teams: ["reds", "wallabies"],
    positions: ["backrow"],
  },
  {
    key: "liamWright",
    title: "Liam Wright",
    firstname: "Liam",
    lastname: "Wright",
    teams: ["reds"],
    positions: ["backrow"],
  },
  {
    key: "joshFlook",
    title: "Josh Flook",
    firstname: "Josh",
    lastname: "Flook",
    teams: ["reds"],
    positions: ["centre", "outsideBack"],
  },
  {
    key: "jockCampbell",
    title: "Jock Campbell",
    firstname: "Jock",
    lastname: "Campbell",
    teams: ["reds"],
    positions: ["outsideBack"],
  },
  {
    key: "suliasiVunivalu",
    title: "Suliasi Vunivalu",
    firstname: "Suliasi",
    lastname: "Vunivalu",
    teams: ["reds", "wallabies"],
    positions: ["outsideBack"],
  },
  {
    key: "jamesO'Connor",
    title: "James O'Connor",
    firstname: "James",
    lastname: "O'Connor",
    teams: ["reds", "wallabies"],
    positions: ["flyhalf", "centre"],
  },
  {
    key: "harryMcLaughlin-Phillips",
    title: "Harry McLaughlin-Phillips",
    firstname: "Harry",
    lastname: "McLaughlin-Phillips",
    teams: ["reds"],
    positions: ["flyhalf"],
  },
  {
    key: "hunterPaisami",
    title: "Hunter Paisami",
    firstname: "Hunter",
    lastname: "Paisami",
    teams: ["reds", "wallabies"],
    positions: ["centre"],
  },
  {
    key: "lawsonCreighton",
    title: "Lawson Creighton",
    firstname: "Lawson",
    lastname: "Creighton",
    teams: ["reds"],
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "tomLynagh",
    title: "Tom Lynagh",
    firstname: "Tom",
    lastname: "Lynagh",
    teams: ["reds"],
    positions: ["flyhalf"],
  },
  {
    key: "isaacHenry",
    title: "Isaac Henry",
    firstname: "Isaac",
    lastname: "Henry",
    teams: ["reds"],
    positions: ["centre"],
  },
  {
    key: "kalaniThomas",
    title: "Kalani Thomas",
    firstname: "Kalani",
    lastname: "Thomas",
    teams: ["reds"],
    positions: ["scrumhalf"],
  },
  {
    key: "ryanSmith",
    title: "Ryan Smith",
    firstname: "Ryan",
    lastname: "Smith",
    teams: ["reds"],
    positions: ["lock"],
  },
  {
    key: "seruUru",
    title: "Seru Uru",
    firstname: "Seru",
    lastname: "Uru",
    teams: ["reds"],
    positions: ["backrow", "lock"],
  },
  {
    key: "connorVest",
    title: "Connor Vest",
    firstname: "Connor",
    lastname: "Vest",
    teams: ["reds"],
    positions: ["lock", "backrow"],
  },
  {
    key: "macGrealy",
    title: "Mac Grealy",
    firstname: "Mac",
    lastname: "Grealy",
    teams: ["reds"],
    positions: ["outsideBack"],
  },
  {
    key: "tajAnnan",
    title: "Taj Annan",
    firstname: "Taj",
    lastname: "Annan",
    teams: ["reds"],
    positions: ["centre"],
  },
  {
    key: "connorAnderson",
    title: "Connor Anderson",
    firstname: "Connor",
    lastname: "Anderson",
    teams: ["reds"],
    positions: ["backrow"],
  },
  {
    key: "cormacDaly",
    title: "Cormac Daly",
    firstname: "Cormac",
    lastname: "Daly",
    teams: ["reds"],
    positions: ["lock"],
  },
  {
    key: "floydAubrey",
    title: "Floyd Aubrey",
    firstname: "Floyd",
    lastname: "Aubrey",
    teams: ["reds"],
    positions: ["outsideBack"],
  },
  {
    key: "frankieGoldsbrough",
    title: "Frankie Goldsbrough",
    firstname: "Frankie",
    lastname: "Goldsbrough",
    teams: ["reds"],
    positions: ["centre"],
  },
  {
    key: "joeBrial",
    title: "Joe Brial",
    firstname: "Joe",
    lastname: "Brial",
    teams: ["reds"],
    positions: ["backrow"],
  },
  {
    key: "johnBryant",
    title: "John Bryant",
    firstname: "John",
    lastname: "Bryant",
    teams: ["reds"],
    positions: ["backrow"],
  },
  {
    key: "louisWerchon",
    title: "Louis Werchon",
    firstname: "Louis",
    lastname: "Werchon",
    teams: ["reds"],
    positions: ["scrumhalf"],
  },
  {
    key: "taineRoiri",
    title: "Taine Roiri",
    firstname: "Taine",
    lastname: "Roiri",
    teams: ["reds"],
    positions: ["lock"],
  },
  {
    key: "timRyan",
    title: "Tim Ryan",
    firstname: "Tim",
    lastname: "Ryan",
    teams: ["reds"],
    positions: ["outsideBack"],
  },
  {
    key: "angusBlyth",
    title: "Angus Blyth",
    firstname: "Angus",
    lastname: "Blyth",
    teams: ["reds"],
    positions: ["lock"],
  },
  {
    key: "richieAsiata",
    title: "Richie Asiata",
    firstname: "Richie",
    lastname: "Asiata",
    teams: ["reds"],
    positions: ["hooker"],
  },
  {
    key: "georgeBlake",
    title: "George Blake",
    firstname: "George",
    lastname: "Blake",
    teams: ["reds"],
    positions: ["prop"],
  },
  {
    key: "maxCraig",
    title: "Max Craig",
    firstname: "Max",
    lastname: "Craig",
    teams: ["reds"],
    positions: ["hooker"],
  },
  {
    key: "massimoDe Lutiis",
    title: "Massimo De Lutiis",
    firstname: "Massimo",
    lastname: "De Lutiis",
    teams: ["reds"],
    positions: ["prop"],
  },
  {
    key: "sefFa'agase",
    title: "Sef Fa'agase",
    firstname: "Sef",
    lastname: "Fa'agase",
    teams: ["reds"],
    positions: ["prop"],
  },
  {
    key: "alexHodgman",
    title: "Alex Hodgman",
    firstname: "Alex",
    lastname: "Hodgman",
    teams: ["reds"],
    positions: ["prop"],
  },
  {
    key: "joshNasser",
    title: "Josh Nasser",
    firstname: "Josh",
    lastname: "Nasser",
    teams: ["reds"],
    positions: ["hooker"],
  },
  {
    key: "zaneNonggorr",
    title: "Zane Nonggorr",
    firstname: "Zane",
    lastname: "Nonggorr",
    teams: ["reds", "wallabies"],
    positions: ["prop"],
  },
  {
    key: "peniRavai",
    title: "Peni Ravai",
    firstname: "Peni",
    lastname: "Ravai",
    teams: ["reds"],
    positions: ["prop"],
  },
  {
    key: "jeffToomaga-Allen",
    title: "Jeff Toomaga-Allen",
    firstname: "Jeff",
    lastname: "Toomaga-Allen",
    teams: ["reds"],
    positions: ["prop"],
  }
]