export const hurricanes = [
  {
    key: "camRoigard",
    title: "Cam Roigard",
    firstname: "Cam",
    lastname: "Roigard",
    teams: ["superRugby", "hurricanes", "allBlacks"],
    positions: ["scrumhalf"],
  },
  {
    key: "kiniNaholo",
    title: "Kini Naholo",
    firstname: "Kini",
    lastname: "Naholo",
    teams: ["superRugby", "hurricanes"],
    positions: ["outsideBack"],
  },
  {
    key: "asafoAumua",
    title: "Asafo Aumua",
    firstname: "Asafo",
    lastname: "Aumua",
    teams: ["superRugby", "hurricanes", "allBlacks"],
    positions: ["hooker"],
  },
  {
    key: "salesiRayasi",
    title: "Salesi Rayasi",
    firstname: "Salesi",
    lastname: "Rayasi",
    teams: ["superRugby", "hurricanes"],
    positions: ["outsideBack"],
  },
  {
    key: "joshuaMoorby",
    title: "Joshua Moorby",
    firstname: "Joshua",
    lastname: "Moorby",
    teams: ["superRugby", "hurricanes"],
    positions: ["outsideBack"],
  },
  {
    key: "jordieBarrett",
    title: "Jordie Barrett",
    firstname: "Jordie",
    lastname: "Barrett",
    teams: ["superRugby", "hurricanes", "allBlacks"],
    positions: ["centre", "outsideBack"],
  },
  {
    key: "billyProctor",
    title: "Billy Proctor",
    firstname: "Billy",
    lastname: "Proctor",
    teams: ["superRugby", "hurricanes"],
    positions: ["centre"],
  },
  {
    key: "xavierNumia",
    title: "Xavier Numia",
    firstname: "Xavier",
    lastname: "Numia",
    teams: ["superRugby", "hurricanes"],
    positions: ["prop"],
  },
  {
    key: "du'plessisKirifi",
    title: "Du'Plessis Kirifi",
    firstname: "Du'Plessis",
    lastname: "Kirifi",
    teams: ["superRugby", "hurricanes"],
    positions: ["backrow"],
  },
  {
    key: "rubenLove",
    title: "Ruben Love",
    firstname: "Ruben",
    lastname: "Love",
    teams: ["superRugby", "hurricanes"],
    positions: ["outsideBack", "flyhalf"],
  },
  {
    key: "devanFlanders",
    title: "Devan Flanders",
    firstname: "Devan",
    lastname: "Flanders",
    teams: ["superRugby", "hurricanes"],
    positions: ["backrow"],
  },
  {
    key: "aidanMorgan",
    title: "Aidan Morgan",
    firstname: "Aidan",
    lastname: "Morgan",
    teams: ["superRugby", "hurricanes"],
    positions: ["flyhalf"],
  },
  {
    key: "braydenIose",
    title: "Brayden Iose",
    firstname: "Brayden",
    lastname: "Iose",
    teams: ["superRugby", "hurricanes"],
    positions: ["backrow"],
  },
  {
    key: "calebDelany",
    title: "Caleb Delany",
    firstname: "Caleb",
    lastname: "Delany",
    teams: ["superRugby", "hurricanes"],
    positions: ["lock", "backrow"],
  },
  {
    key: "peterLakai",
    title: "Peter Lakai",
    firstname: "Peter",
    lastname: "Lakai",
    teams: ["superRugby", "hurricanes"],
    positions: ["backrow"],
  },
  {
    key: "brettCameron",
    title: "Brett Cameron",
    firstname: "Brett",
    lastname: "Cameron",
    teams: ["superRugby", "hurricanes"],
    positions: ["flyhalf"],
  },
  {
    key: "bailynSullivan",
    title: "Bailyn Sullivan",
    firstname: "Bailyn",
    lastname: "Sullivan",
    teams: ["superRugby", "hurricanes"],
    positions: ["centre"],
  },
  {
    key: "harryGodfrey",
    title: "Harry Godfrey",
    firstname: "Harry",
    lastname: "Godfrey",
    teams: ["superRugby", "hurricanes"],
    positions: ["outsideBack", "flyhalf"],
  },
  {
    key: "jamesTucker",
    title: "James Tucker",
    firstname: "James",
    lastname: "Tucker",
    teams: ["superRugby", "hurricanes"],
    positions: ["lock"],
  },
  {
    key: "tkHowden",
    title: "TK Howden",
    firstname: "TK",
    lastname: "Howden",
    teams: ["superRugby", "hurricanes"],
    positions: ["backrow"],
  },
  {
    key: "peterUmaga-Jensen",
    title: "Peter Umaga-Jensen",
    firstname: "Peter",
    lastname: "Umaga-Jensen",
    teams: ["superRugby", "hurricanes"],
    positions: ["centre"],
  },
  {
    key: "danielSinkinson",
    title: "Daniel Sinkinson",
    firstname: "Daniel",
    lastname: "Sinkinson",
    teams: ["superRugby", "hurricanes"],
    positions: ["outsideBack"],
  },
  {
    key: "isaiaWalker-Leawere",
    title: "Isaia Walker-Leawere",
    firstname: "Isaia",
    lastname: "Walker-Leawere",
    teams: ["superRugby", "hurricanes"],
    positions: ["lock"],
  },
  {
    key: "rileyHiggins",
    title: "Riley Higgins",
    firstname: "Riley",
    lastname: "Higgins",
    teams: ["superRugby", "hurricanes"],
    positions: ["centre"],
  },
  {
    key: "justinSangster",
    title: "Justin Sangster",
    firstname: "Justin",
    lastname: "Sangster",
    teams: ["superRugby", "hurricanes"],
    positions: ["lock"],
  },
  {
    key: "benGrant",
    title: "Ben Grant",
    firstname: "Ben",
    lastname: "Grant",
    teams: ["superRugby", "hurricanes"],
    positions: ["lock"],
  },
  {
    key: "bradShields",
    title: "Brad Shields",
    firstname: "Brad",
    lastname: "Shields",
    teams: ["superRugby", "hurricanes"],
    positions: ["backrow"],
  },
  {
    key: "joshTaula",
    title: "Josh Taula",
    firstname: "Josh",
    lastname: "Taula",
    teams: ["superRugby", "hurricanes"],
    positions: ["lock"],
  },
  {
    key: "richardJudd",
    title: "Richard Judd",
    firstname: "Richard",
    lastname: "Judd",
    teams: ["superRugby", "hurricanes"],
    positions: ["scrumhalf"],
  },
  {
    key: "tjPerenara",
    title: "TJ Perenara",
    firstname: "TJ",
    lastname: "Perenara",
    teams: ["superRugby", "hurricanes"],
    positions: ["scrumhalf"],
  },
  {
    key: "ngatunganePunivai",
    title: "Ngatungane Punivai",
    firstname: "Ngatungane",
    lastname: "Punivai",
    teams: ["superRugby", "hurricanes"],
    positions: ["outsideBack"],
  },
  {
    key: "jacobDevery",
    title: "Jacob Devery",
    firstname: "Jacob",
    lastname: "Devery",
    teams: ["superRugby", "hurricanes"],
    positions: ["hooker"],
  },
  {
    key: "sialeLauaki",
    title: "Siale Lauaki",
    firstname: "Siale",
    lastname: "Lauaki",
    teams: ["superRugby", "hurricanes"],
    positions: ["prop"],
  },
  {
    key: "tyrelLomax",
    title: "Tyrel Lomax",
    firstname: "Tyrel",
    lastname: "Lomax",
    teams: ["superRugby", "hurricanes", "allBlacks"],
    positions: ["prop"],
  },
  {
    key: "tevitaMafileo",
    title: "Tevita Mafileo",
    firstname: "Tevita",
    lastname: "Mafileo",
    teams: ["superRugby", "hurricanes"],
    positions: ["prop"],
  },
  {
    key: "jamesO'Reilly",
    title: "James O'Reilly",
    firstname: "James",
    lastname: "O'Reilly",
    teams: ["superRugby", "hurricanes"],
    positions: ["hooker"],
  },
  {
    key: "pouriRakete-Stones",
    title: "Pouri Rakete-Stones",
    firstname: "Pouri",
    lastname: "Rakete-Stones",
    teams: ["superRugby", "hurricanes"],
    positions: ["prop"],
  },
  {
    key: "pasilioTosi",
    title: "Pasilio Tosi",
    firstname: "Pasilio",
    lastname: "Tosi",
    teams: ["superRugby", "hurricanes"],
    positions: ["prop"],
  }
]