export const force = [
  {
    key: "carloTizzano",
    title: "Carlo Tizzano",
    firstname: "Carlo",
    lastname: "Tizzano",
    teams: ["force"],
    positions: ["backrow"],
  },
  {
    key: "willHarris",
    title: "Will Harris",
    firstname: "Will",
    lastname: "Harris",
    teams: ["force"],
    positions: ["backrow"],
  },
  {
    key: "samSpink",
    title: "Sam Spink",
    firstname: "Sam",
    lastname: "Spink",
    teams: ["force"],
    positions: ["centre"],
  },
  {
    key: "jeremyWilliams",
    title: "Jeremy Williams",
    firstname: "Jeremy",
    lastname: "Williams",
    teams: ["force"],
    positions: ["lock"],
  },
  {
    key: "harryPotter",
    title: "Harry Potter",
    firstname: "Harry",
    lastname: "Potter",
    teams: ["force"],
    positions: ["outsideBack"],
  },
  {
    key: "santiagoMedrano",
    title: "Santiago Medrano",
    firstname: "Santiago",
    lastname: "Medrano",
    teams: ["force"],
    positions: ["prop"],
  },
  {
    key: "issakFines-Leleiwasa",
    title: "Issak Fines-Leleiwasa",
    firstname: "Issak",
    lastname: "Fines-Leleiwasa",
    teams: ["force", "wallabies"],
    positions: ["scrumhalf"],
  },
  {
    key: "benDonaldson",
    title: "Ben Donaldson",
    firstname: "Ben",
    lastname: "Donaldson",
    teams: ["force", "wallabies"],
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "chaseTiatia",
    title: "Chase Tiatia",
    firstname: "Chase",
    lastname: "Tiatia",
    teams: ["force"],
    positions: ["outsideBack"],
  },
  {
    key: "hamishStewart",
    title: "Hamish Stewart",
    firstname: "Hamish",
    lastname: "Stewart",
    teams: ["force"],
    positions: ["centre", "flyhalf"],
  },
  {
    key: "timAnstee",
    title: "Tim Anstee",
    firstname: "Tim",
    lastname: "Anstee",
    teams: ["force"],
    positions: ["backrow"],
  },
  {
    key: "felixKalapu",
    title: "Felix Kalapu",
    firstname: "Felix",
    lastname: "Kalapu",
    teams: ["force"],
    positions: ["lock"],
  },
  {
    key: "bayleyKuenzle",
    title: "Bayley Kuenzle",
    firstname: "Bayley",
    lastname: "Kuenzle",
    teams: ["force"],
    positions: ["centre", "flyhalf", "outsideBack"],
  },
  {
    key: "michaelWells",
    title: "Michael Wells",
    firstname: "Michael",
    lastname: "Wells",
    teams: ["force"],
    positions: ["backrow"],
  },
  {
    key: "maxBurey",
    title: "Max Burey",
    firstname: "Max",
    lastname: "Burey",
    teams: ["force"],
    positions: ["flyhalf", "outsideBack"],
  },
  {
    key: "nicWhite",
    title: "Nic White",
    firstname: "Nic",
    lastname: "White",
    teams: ["force", "wallabies"],
    positions: ["scrumhalf"],
  },
  {
    key: "ollieCallan",
    title: "Ollie Callan",
    firstname: "Ollie",
    lastname: "Callan",
    teams: ["force"],
    positions: ["backrow"],
  },
  {
    key: "georgePoolman",
    title: "George Poolman",
    firstname: "George",
    lastname: "Poolman",
    teams: ["force"],
    positions: ["outsideBack"],
  },
  {
    key: "ianPrior",
    title: "Ian Prior",
    firstname: "Ian",
    lastname: "Prior",
    teams: ["force"],
    positions: ["scrumhalf"],
  },
  {
    key: "jacksonPugh",
    title: "Jackson Pugh",
    firstname: "Jackson",
    lastname: "Pugh",
    teams: ["force"],
    positions: ["lock", "backrow"],
  },
  {
    key: "lopetiFaifua",
    title: "Lopeti Faifua",
    firstname: "Lopeti",
    lastname: "Faifua",
    teams: ["force"],
    positions: ["lock"],
  },
  {
    key: "izackRodda",
    title: "Izack Rodda",
    firstname: "Izack",
    lastname: "Rodda",
    teams: ["force", "wallabies"],
    positions: ["lock"],
  },
  {
    key: "nikolaiFoliaki",
    title: "Nikolai Foliaki",
    firstname: "Nikolai",
    lastname: "Foliaki",
    teams: ["force"],
    positions: ["centre"],
  },
  {
    key: "campbellParata",
    title: "Campbell Parata",
    firstname: "Campbell",
    lastname: "Parata",
    teams: ["force"],
    positions: ["flyhalf"],
  },
  {
    key: "henryO'Donnell",
    title: "Henry O'Donnell",
    firstname: "Henry",
    lastname: "O'Donnell",
    teams: ["force"],
    positions: ["centre"],
  },
  {
    key: "henryRobertson",
    title: "Henry Robertson",
    firstname: "Henry",
    lastname: "Robertson",
    teams: ["force"],
    positions: ["scrumhalf"],
  },
  {
    key: "ollieCummins",
    title: "Ollie Cummins",
    firstname: "Ollie",
    lastname: "Cummins",
    teams: ["force"],
    positions: ["centre"],
  },
  {
    key: "papillonSevele",
    title: "Papillon Sevele",
    firstname: "Papillon",
    lastname: "Sevele",
    teams: ["force"],
    positions: ["backrow"],
  },
  {
    key: "reesjanPasitoa",
    title: "Reesjan Pasitoa",
    firstname: "Reesjan",
    lastname: "Pasitoa",
    teams: ["force"],
    positions: ["flyhalf", "centre", "outsideBack"],
  },
  {
    key: "siosifaAmone",
    title: "Siosifa Amone",
    firstname: "Siosifa",
    lastname: "Amone",
    teams: ["force"],
    positions: ["prop"],
  },
  {
    key: "charlieHancock",
    title: "Charlie Hancock",
    firstname: "Charlie",
    lastname: "Hancock",
    teams: ["force"],
    positions: ["prop"],
  },
  {
    key: "harryHoopert",
    title: "Harry Hoopert",
    firstname: "Harry",
    lastname: "Hoopert",
    teams: ["force"],
    positions: ["prop"],
  },
  {
    key: "tomHorton",
    title: "Tom Horton",
    firstname: "Tom",
    lastname: "Horton",
    teams: ["force"],
    positions: ["hooker"],
  },
  {
    key: "feletiKaitu'u",
    title: "Feleti Kaitu'u",
    firstname: "Feleti",
    lastname: "Kaitu'u",
    teams: ["force"],
    positions: ["hooker"],
  },
  {
    key: "atuMoli",
    title: "Atu Moli",
    firstname: "Atu",
    lastname: "Moli",
    teams: ["force"],
    positions: ["prop"],
  },
  {
    key: "marleyPearce",
    title: "Marley Pearce",
    firstname: "Marley",
    lastname: "Pearce",
    teams: ["force"],
    positions: ["prop"],
  },
  {
    key: "angusWagner",
    title: "Angus Wagner",
    firstname: "Angus",
    lastname: "Wagner",
    teams: ["force"],
    positions: ["prop"],
  }
]